### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by samiit** [LiuYangMage/RLFluidControl#1]
Hi,

Thanks very much for releasing your code here. I found it from your paper. I had a question: does your code allow visualization within processing. Can you suggest some kind of helper file to know how to use it?

Thanks again.

Sam

**Comment by hyperpotato** [comment]
Hi, Sam,

On behalf of my coauthors, first, we want to thank you for your interest on our work.

It allows directly visualizations in processing directly, currently we only save dozens of image at the end of each training episode in order to save time. But if you want to demonstrate the visualization of each time step, in the file “clientCFD.pde” line 38, add one line code of
test.display();

Also see the attached image
![clientCFD](https://user-images.githubusercontent.com/17143659/81226104-4dc91680-8fb8-11ea-8328-d60679b8f2a6.png)

Also if you are interested in the CFD processing code, it is based on a 2D BDIM code “lilypad” developed by Dr. Gab Weymouth. And you can find the open-source of the code in the following GitHub link.

https://github.com/weymouth/lily-pad

[cid:F178C925-C6BF-41E0-ADDC-0080EAE81807@hsd1.ma.comcast.net]


On May 6, 2020, at 3:29 PM, Sam Mathew <notifications@github.com<mailto:notifications@github.com>> wrote:





Hi,

Thanks very much for releasing your code here. I found it from your paper. I had a question: does your code allow visualization within processing. Can you suggest some kind of helper file to know how to use it?

Thanks again.

Sam

**Comment by samiit** [comment]
Thanks for your quick response. I could visualize it now with the necessary changes.

Thank you also for pointing me to LilyPad. I had worked some years ago on [controlling wake vortices](https://iopscience.iop.org/article/10.1088/0169-5983/48/1/015510/meta) using the conventional CFD tools, and though I knew of BDIM back then, I wasn't sure how mature it was; from what I gather, it has matured much! With this approach, I hope to see how new control algorithms can be implemented with a much more efficient CFD code.

Since I moved on to ML and while checking more on RL for control, was interested whether the fluid dynamics community has caught on with RL. And sure they did! All the best with your publication. I will surely ping you or suggest a few ideas if you are interested.

Sam
